FROM ghcr.io/spmzt/freebsd-baseutils:latest
LABEL org.opencontainers.image.source https://github.com/spmzt/images \
    org.opencontainers.image.title="FreeBSD Golang" \
    org.opencontainers.image.description="FreeBSD golang image" \
    org.opencontainers.image.authors="spmzt"
RUN pkg install -y go && \
    pkg clean -ay
