FROM ghcr.io/spmzt/freebsd-baseutils:latest
LABEL org.opencontainers.image.source="https://github.com/spmzt/images" \
    org.opencontainers.image.title="FreeBSD PostgreSQL 18" \
    org.opencontainers.image.description="FreeBSD PostgreSQL18 image" \
    org.opencontainers.image.authors="spmzt" \
    org.freebsd.jail.allow.sysvipc="true"
RUN pkg install -y postgresql18-server postgresql18-client && \
    pkg-cleanup && \
    install -d -o postgres -g postgres -m 0755 /var/db/postgres
COPY --chmod=0755 postgres18/entrypoint.sh /usr/local/bin/entrypoint.sh
ENV PGDATA=/var/db/postgres/data18
VOLUME /var/db/postgres
USER postgres
WORKDIR /var/db/postgres
STOPSIGNAL SIGINT
EXPOSE 5432
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["postgres"]
