FROM ghcr.io/spmzt/freebsd-baseutils:latest
LABEL org.opencontainers.image.source https://github.com/spmzt/images \
    org.opencontainers.image.title="FreeBSD Node 22" \
    org.opencontainers.image.description="FreeBSD node 22 image" \
    org.opencontainers.image.authors="spmzt"
RUN pkg install -y node22 npm-node22 && \
    pkg clean -ay
