ARG OWNER=spmzt
ARG REPO=images

FROM ghcr.io/spmzt/freebsd-baseutils:latest
ARG OWNER
ARG REPO
LABEL org.opencontainers.image.source https://github.com/$OWNER/$REPO
RUN pkg install -y py311-pip py311-setuptools \
    py311-wheel py311-cryptography && \
    pkg clean -ay
