FROM ghcr.io/spmzt/freebsd-baseutils:latest
LABEL org.opencontainers.image.source https://github.com/spmzt/images \
    org.opencontainers.image.title="FreeBSD nginx" \
    org.opencontainers.image.description="FreeBSD nginx image" \
    org.opencontainers.image.authors="spmzt"
RUN pkg install -y nginx && \
    pkg clean -ay
RUN sed -i'' -e '$s|^\}$|    include /usr/local/etc/nginx/conf.d/*.conf;\n}|g' \
    /usr/local/etc/nginx/nginx.conf
EXPOSE 80
