FROM ghcr.io/spmzt/freebsd-baseutils:latest
LABEL org.opencontainers.image.source https://github.com/spmzt/images \
    org.opencontainers.image.title="FreeBSD Node 20" \
    org.opencontainers.image.description="FreeBSD node 20 image" \
    org.opencontainers.image.authors="spmzt"
RUN pkg install -y node20 npm-node20 && \
    pkg clean -ay
