FROM ghcr.io/spmzt/freebsd-baseutils:latest
LABEL org.opencontainers.image.source="https://github.com/spmzt/images" \
    org.opencontainers.image.title="FreeBSD Freenginx" \
    org.opencontainers.image.description="FreeBSD freenginx image" \
    org.opencontainers.image.authors="spmzt"
RUN pkg install -y freenginx && \
    pkg-cleanup
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log
EXPOSE 80
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
