FROM ghcr.io/spmzt/freebsd-baseutils:latest
LABEL org.opencontainers.image.source https://github.com/spmzt/images \
    org.opencontainers.image.title="FreeBSD Freenginx" \
    org.opencontainers.image.description="FreeBSD freenginx image" \
    org.opencontainers.image.authors="spmzt"
RUN pkg install -y freenginx && \
    pkg clean -ay
