ARG OWNER=spmzt
ARG REPO=images

FROM ghcr.io/spmzt/freebsd-base:latest
ARG OWNER
ARG REPO
LABEL org.opencontainers.image.source https://github.com/$OWNER/$REPO
RUN pkg install -y FreeBSD-utilities && \
    pkg clean -ay
