FROM ghcr.io/spmzt/freebsd-base:latest
LABEL org.opencontainers.image.source https://github.com/spmzt/images \
    org.opencontainers.image.title="FreeBSD Baseutils" \
    org.opencontainers.image.description="FreeBSD notoolchain image with FreeBSD-utilities" \
    org.opencontainers.image.authors="spmzt"
RUN pkg install -y FreeBSD-utilities && \
    pkg clean -ay
