name: FreeBSD OCI Images

on:
  push:
    branches: [ "main" ]
  workflow_call:
    inputs:
      image_name:
        description: 'Image name (e.g., base, python)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free disk space
        uses: endersonmenezes/free-disk-space@v3
        with:
          remove_tool_cache: true
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox mono-complete"
          remove_packages_one_command: true
          rm_cmd: rmz

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download pre-build artifact
        if: inputs.pre_artifact_name != ''
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.pre_artifact_name }}
          path: ${{ inputs.pre_artifact_path }}

      - name: Prepare VM data directory
        run: sudo mkdir -p /mnt/freebsd-vm && sudo chmod 777 /mnt/freebsd-vm

      - name: build oci image
        uses: vmactions/freebsd-vm@v1.4.6
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
          REGISTRY: ghcr.io
        with:
          usesh: true
          copyback: true
          data-dir: /mnt/freebsd-vm
          #debug-on-error: true
          #vnc-password: ${{ secrets.VNC_PASSWORD }}
          envs: "AUTH_TOKEN USERNAME REGISTRY"
          prepare: |
            pkg install -y podman-suite
            echo "${AUTH_TOKEN}" | buildah login ${REGISTRY} -u ${AUTH_TOKEN} --password-stdin
          run: |
            set -e

            fetch https://download.freebsd.org/snapshots/OCI-IMAGES/16.0-CURRENT/amd64/Latest/FreeBSD-16.0-CURRENT-amd64-container-image-notoolchain.txz
            BASE_IMAGE=$(podman load --input FreeBSD-16.0-CURRENT-amd64-container-image-notoolchain.txz | sed -e 's/Loaded image: //g')

            IMAGE_PREFIX="${REGISTRY}/${USERNAME}/freebsd"
            buildah tag ${BASE_IMAGE} ${IMAGE_PREFIX}-base:`date -I`
            buildah tag ${BASE_IMAGE} ${IMAGE_PREFIX}-base:latest
            buildah push ${IMAGE_PREFIX}-base:`date -I` ${IMAGE_PREFIX}-base:latest

            # XXX: Builds below should be in a Makefile
            cd python
            buildah build --layers --network=host -t ${IMAGE_PREFIX}-py311:`date -I` -t ${IMAGE_PREFIX}-py311:latest
            buildah push ${IMAGE_PREFIX}-py311:`date -I` ${IMAGE_PREFIX}-py311:latest
            cd ..

            cd golang
            buildah build --layers --network=host -t ${REGISTRY}/${USERNAME}/freebsd-go:`date -I` -t ${REGISTRY}/${USERNAME}/freebsd-go:latest
            buildah push ${IMAGE_PREFIX}-go:`date -I` ${IMAGE_PREFIX}-go:latest
            cd ..

            cd node
            buildah build --layers --network=host -t ${REGISTRY}/${USERNAME}/freebsd-node20:`date -I` -t ${REGISTRY}/${USERNAME}/freebsd-node20:latest
            buildah push ${IMAGE_PREFIX}-node20:`date -I` ${IMAGE_PREFIX}-node20:latest
            cd ..
