name: FreeBSD OCI Images

on:
  push:
    branches: [ "main" ]
  workflow_call:
    inputs:
      image_name:
        description: 'Image name (e.g., base, python)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free disk space
        uses: endersonmenezes/free-disk-space@v3
        with:
          remove_tool_cache: true
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox mono-complete"
          remove_packages_one_command: true
          rm_cmd: rmz

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: build oci image
        uses: vmactions/freebsd-vm@v1.4.6
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
          REGISTRY: ghcr.io
          OS_VER: 16.0-CURRENT
        with:
          usesh: true
          #debug-on-error: true
          #vnc-password: ${{ secrets.VNC_PASSWORD }}
          envs: "AUTH_TOKEN USERNAME REGISTRY OS_VER"
          prepare: |
            pkg install -y podman-suite
            echo "${AUTH_TOKEN}" | buildah login ${REGISTRY} -u ${AUTH_TOKEN} --password-stdin
          run: ./make.sh -d
